version: "3.2"
services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: postgres
  redis:
    image: redis:5.0.5-alpine
    ports:
      - 6379:6379
